{{- if .Values.externalDns.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-external-dns
subjects:
- kind: ServiceAccount
  name: {{ .Values.iq_server.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-external-dns
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-external-dns
    spec:
      serviceAccountName: {{ .Values.iq_server.serviceAccountName }}
      automountServiceAccountToken: true
      containers:
      - name: {{ .Release.Name }}-external-dns
        image: bitnami/external-dns:0.7.1
        args:
          {{- range .Values.externalDns.args }}
          - {{ tpl . $ }}
          {{- end }}
{{- end }}
