{{- if and (.Values.iq_server.persistence.persistentVolumeName) (not .Values.iq_server.persistence.existingPersistentVolumeName) (not .Values.iq_server.persistence.existingPersistentVolumeClaimName) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.iq_server.persistence.persistentVolumeName }}
  annotations:
    "helm.sh/resource-policy": {{ .Values.iq_server.persistence.persistentVolumeRetainPolicy }}
spec:
  volumeMode: Filesystem
  storageClassName: {{- if .Values.iq_server.persistence.storageClassName }} {{ .Values.iq_server.persistence.storageClassName }} {{- else }} ""{{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.iq_server.persistence.persistentVolumeClaimName }}
  capacity:
    storage: {{ .Values.iq_server.persistence.size }}
  accessModes:
  {{- if .Values.iq_server.persistence.accessModes}}
    {{- range .Values.iq_server.persistence.accessModes }}
    - {{ . }}
    {{- end}}
  {{- else if and ((.Values.iq_server.persistence).hostPath).path ((.Values.iq_server.persistence).hostPath).type}}
    - ReadWriteOnce
  {{- else }}
    - ReadWriteMany
  {{- end }}
  {{- if ((.Values.iq_server.persistence).cephfs).monitors }}
  cephfs:
    readOnly: false
    {{- if .Values.iq_server.persistence.cephfs.path }}
    path: {{ .Values.iq_server.persistence.cephfs.path }}
    {{- end }}
    {{- if .Values.iq_server.persistence.cephfs.secretFile }}
    secretFile: {{ .Values.iq_server.persistence.cephfs.secretFile }}
    {{- end }}
    {{- if .Values.iq_server.persistence.cephfs.secretRef }}
    secretRef: {{ .Values.iq_server.persistence.cephfs.secretRef }}
    {{- end}}
    {{- if .Values.iq_server.persistence.cephfs.user }}
    user: {{ .Values.iq_server.persistence.cephfs.user }}
    {{- end}}
    monitors:
      {{- range .Values.iq_server.persistence.cephfs.monitors }}
      - {{ . }}
      {{- end}}
  {{- else if and (.Values.iq_server.persistence.csi).driver (.Values.iq_server.persistence.csi).volumeHandle }}
  csi:
    readOnly: false
    driver: {{ .Values.iq_server.persistence.csi.driver }}
    volumeHandle: {{ .Values.iq_server.persistence.csi.volumeHandle }}
    fsType: {{ .Values.iq_server.persistence.csi.fsType }}
    {{- if and (((.Values.iq_server.persistence).csi).controllerExpandSecretRef).namespace (((.Values.iq_server.persistence).csi).controllerExpandSecretRef).name }}
    controllerExpandSecretRef:
      namespace: {{ .Values.iq_server.persistence.csi.controllerExpandSecretRef.namespace }}
      name: {{ .Values.iq_server.persistence.csi.controllerExpandSecretRef.name }}
    {{- end}}
    {{- if and (((.Values.iq_server.persistence).csi).controllerPublishSecretRef).namespace (((.Values.iq_server.persistence).csi).controllerPublishSecretRef).name }}
    controllerPublishSecretRef:
      namespace: {{ .Values.iq_server.persistence.csi.controllerPublishSecretRef.namespace }}
      name: {{ .Values.iq_server.persistence.csi.controllerPublishSecretRef.name }}
    {{- end}}
    {{- if and (((.Values.iq_server.persistence).csi).nodePublishSecretRef).namespace (((.Values.iq_server.persistence).csi).nodePublishSecretRef).name }}
    nodePublishSecretRef:
      namespace: {{ .Values.iq_server.persistence.csi.nodePublishSecretRef.namespace }}
      name: {{ .Values.iq_server.persistence.csi.nodePublishSecretRef.name }}
    {{- end}}
    {{- if and (((.Values.iq_server.persistence).csi).nodeStageSecretRef).namespace (((.Values.iq_server.persistence).csi).nodeStageSecretRef).name }}
    nodeStageSecretRef:
      namespace: {{ .Values.iq_server.persistence.csi.nodeStageSecretRef.namespace }}
      name: {{ .Values.iq_server.persistence.csi.nodeStageSecretRef.name }}
    {{- end}}
    {{- if .Values.iq_server.persistence.csi.volumeAttributes }}
    volumeAttributes:
{{ toYaml .Values.iq_server.persistence.csi.volumeAttributes | nindent 6 }}
    {{- end}}
  {{- else if and ((.Values.iq_server.persistence).nfs).server ((.Values.iq_server.persistence).nfs).path }}
  nfs:
    readOnly: false
    server: {{ .Values.iq_server.persistence.nfs.server }}
    path: {{ .Values.iq_server.persistence.nfs.path }}
  {{- if ((.Values.iq_server.persistence).nfs).mountOptions }}
  {{- with .Values.iq_server.persistence.nfs.mountOptions }}
  mountOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- else if and ((.Values.iq_server.persistence).hostPath).path ((.Values.iq_server.persistence).hostPath).type }}
  hostPath:
    path: {{ .Values.iq_server.persistence.hostPath.path }}
    type: {{ .Values.iq_server.persistence.hostPath.type }}
  {{- end}}
  {{- if ((.Values.iq_server.persistence).nodeAffinity).nodeSelectorTerms }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
{{ toYaml .Values.iq_server.persistence.nodeAffinity.nodeSelectorTerms | nindent 8 }}
  {{- end }}
{{- end }}
