apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-iq-server-application-service
  {{- with .Values.iq_server.applicationServiceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.iq_server.serviceType }}
  selector:
    name: {{ .Release.Name }}-iq-server
  ports:
    {{- range $index, $value := (.Values.iq_server.config.server.applicationConnectors) }}
    - name: iq-server-app-port-{{- $index }}
      protocol: TCP
      port: {{ $value.port }}
      targetPort: application-{{- $index }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-iq-server-admin-service
  {{- with .Values.iq_server.adminServiceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.iq_server.serviceType }}
  selector:
    name: {{ .Release.Name }}-iq-server
  ports:
    {{- range $index, $value := (.Values.iq_server.config.server.adminConnectors) }}
    - name: iq-server-adm-port-{{- $index }}
      protocol: TCP
      port: {{ $value.port }}
      targetPort: admin-{{- $index }}
    {{- end }}
