{{- if .Values.iq_server.persistence.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.iq_server.persistence.storageClass.name | default (printf "%s-storageclass" .Release.Name) }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.iq_server.persistence.storageClass.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.iq_server.persistence.storageClass.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: {{ required "iq_server.persistence.storageClass.provisioner is required when storageClass.create is true" .Values.iq_server.persistence.storageClass.provisioner }}
reclaimPolicy: {{ .Values.iq_server.persistence.storageClass.reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ .Values.iq_server.persistence.storageClass.volumeBindingMode | default "Immediate" }}
allowVolumeExpansion: {{ .Values.iq_server.persistence.storageClass.allowVolumeExpansion | default false }}
{{- with .Values.iq_server.persistence.storageClass.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.iq_server.persistence.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
